#!/usr/bin/env python3
"""
Move the site to extensionless URLs (/plantar-fasciitis, not
/plantar-fasciitis.html) and generate the 301s that retire the old ones.

WHY NOW: the site went live on wasatchfai.com today and was noindexed until an
hour before this ran, so almost nothing is in Google's index yet. Changing URLs
is never cheaper than this. It also restores the URL shape the previous Wix site
used -- every archived Wix URL was extensionless -- so legacy inbound links and
any residual ranking signal land on the right page instead of a redirect.

Netlify already serves BOTH forms with a 200, which is duplicate content: every
page is reachable at two URLs. This makes the extensionless form canonical and
301s the .html form to it.

The .html redirects need force (the `!` suffix). Netlify resolves static files
BEFORE consulting redirects, and /foo.html IS a static file, so an unforced rule
would never fire. There is no loop risk: the rule matches only the literal
/foo.html, and /foo is served from foo.html without a redirect.

Idempotent. Run from the repo root:  python3 build-extensionless.py
"""
import glob
import pathlib
import re

ROOT = pathlib.Path(__file__).parent
BASE = "https://www.wasatchfai.com"

# --------------------------------------------------------------- inventory ---
def pages():
    out = []
    for f in sorted(glob.glob("*.html")) + sorted(glob.glob("post/*.html")) \
            + sorted(glob.glob("heel-pain-procedure/*.html")):
        out.append(f)
    return out


def pretty(rel):
    """foo.html -> /foo ; index.html -> / ; dir/index.html -> /dir/"""
    if rel == "index.html":
        return "/"
    if rel.endswith("/index.html"):
        return "/" + rel[: -len("index.html")]
    return "/" + rel[:-len(".html")]


# ------------------------------------------------------------ html rewrite ---
ABS_INDEX = re.compile(re.escape(BASE) + r"/index\.html")
ABS_ANY = re.compile(re.escape(BASE) + r"/([A-Za-z0-9._/-]+?)\.html")
# href/src values ending in .html, optionally with a #fragment
REL_ATTR = re.compile(r'(href|src)=(["\'])([^"\']*?)\.html(#[^"\']*)?\2')


def rewrite_html(text):
    # 1. absolute canonical / og:url / schema @id + url values
    text = ABS_INDEX.sub(BASE + "/", text)
    text = ABS_ANY.sub(lambda m: f"{BASE}/{m.group(1)}", text)

    # 2. relative hrefs
    def rel(m):
        attr, q, path, frag = m.group(1), m.group(2), m.group(3), m.group(4) or ""
        # index.html in any relative form points at the site root
        if path == "index" or path.endswith("/index"):
            return f'{attr}={q}/{frag}{q}'
        return f'{attr}={q}{path}{frag}{q}'
    text = REL_ATTR.sub(rel, text)
    return text


# ---------------------------------------------------------------- redirects --
LEGACY = [
    # Wix-era URLs found in the Wayback archive that have no direct equivalent.
    ("/heal-pain", "/heel-pain", "the old site shipped this typo of heel-pain"),
    ("/post", "/blog", "Wix used /post as the blog index; ours is /blog"),
    ("/old-home", "/", "abandoned Wix draft page"),
    ("/product-page/performance-orthotics", "/shop", "Wix Stores product page"),
    ("/blog/categories/*", "/blog", "Wix blog category archives"),
    ("/blog/page/*", "/blog", "Wix blog pagination"),
]


def build_redirects(files):
    lines = [
        "# Generated by build-extensionless.py -- do not hand-edit.",
        "#",
        "# 1. Retire the .html URLs in favour of extensionless ones.",
        "#    The `!` forces the rule: Netlify resolves static files before",
        "#    redirects, and /foo.html is a static file, so an unforced rule",
        "#    would never fire. /foo still serves foo.html directly, so there",
        "#    is no loop.",
        "",
    ]
    for f in files:
        target = pretty(f)
        lines.append(f"/{f}".ljust(66) + f"{target}".ljust(46) + "301!")
    lines += [
        "",
        "# 2. Legacy URLs from the previous Wix site (found via the Wayback CDX",
        "#    index). These have no direct equivalent in the new structure.",
        "",
    ]
    for frm, to, why in LEGACY:
        lines.append(f"# {why}")
        lines.append(frm.ljust(66) + to.ljust(46) + "301")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------- main --
if __name__ == "__main__":
    files = pages()

    changed = 0
    for f in files:
        p = ROOT / f
        s = p.read_text(encoding="utf-8")
        new = rewrite_html(s)
        if new != s:
            p.write_text(new, encoding="utf-8")
            changed += 1
    print(f"rewrote links/canonicals in {changed}/{len(files)} pages")

    # llms.txt carries absolute URLs too
    llms = ROOT / "llms.txt"
    s = llms.read_text(encoding="utf-8")
    new = ABS_INDEX.sub(BASE + "/", s)
    new = ABS_ANY.sub(lambda m: f"{BASE}/{m.group(1)}", new)
    if new != s:
        llms.write_text(new, encoding="utf-8")
        print("updated llms.txt")

    (ROOT / "_redirects").write_text(build_redirects(files), encoding="utf-8")
    print(f"wrote _redirects ({len(files)} .html retirements + {len(LEGACY)} legacy rules)")
